baseURL = "https://brandongiesing.com/"
languageCode = "en-US"
title = "BrandonGiesing.com"
theme = ["cosicast","toxic-swamp","after-dark"]

[params.hackcss]
  disabled = false
  mode = "hack"
  palette = "cosicast"

disqusShortname = "brandongiesing"
footnoteReturnLinkContents = "↩" # Provides a nicer footnote return link
enableRobotsTXT = true # Suggested, enable robots.txt file

[params.layout.menu.main]
  hidden = false # set `false` or remove to show section menu

[params.layout.home]
hide_blog = true

[[params.layout.home.section]]
  type = "post"
  limit = 3
  weight = 1
  thumbs = ["fill", "400x400"] # Optional, thumbnail image processing

[params.layout.post.featured]
  limit = 4
  items = [
    "2019-06-07-stadia",
    "2018-06-23-hat-stitch-2018-update",
    "2017-10-02-twit-2017-thoughts",
  ]
  thumbs = ["fill", "400x400"] # Optional, thumbnail image processing

[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Blog"
  weight = 2
  identifier = "blog"
  url = "/post"
[[menu.main]]
  name = "CosiCast"
  weight = 3
  identifier = "cosicast"
  url = "/cosicast"
[[menu.main]]
  name = "Money Routine"
  weight = 4
  identifier = "money"
  url = "/money/"
[[menu.main]]
  name = "Projects"
  weight = 5
  identifier = "projects"
  url = "/projects"
[[menu.main]]
  name = "Support Me"
  weight = 5
  identifier = "supportme"
  url = "/supportme"
[[menu.main]]
  name = "Search"
  weight = 6
  identifier = "search"
  url = "/search"

[permalinks]
  post = "/:year/:month/:day/:title/"

[params]
  author = "Brandon Giesing"
  hide_author = true
  show_menu = true
  powered_by = false

[params.seo]
  telegram_channel = "CosiCorner"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS", "JSON"]

[privacy]
  [privacy.instagram]
    simple = true
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true

[params.modules.toxic_swamp]
  enabled = false
  address = "48qsTAhshB17UtbDbfQx7xJugDW6toex3jkTCC2kRpnFHP8aZnLbrcmDP8PvQs8XpjRggTV2DS1VSNGFxRkVYQjv1DvRSHH"
