[build]
  publish = "public"
  command = "hugo --minify"
# build a preview of the site [hugo --buildFuture]
[context.deploy-preview]
  command = "hugo --minify --buildFuture"
# The default version you use for production if you don't use context
[build.environment]
  HUGO_VERSION = "0.163.0"
  RUBY_VERSION = "4.0.5"
# The version you use for production
[context.production.environment]
  HUGO_VERSION = "0.163.0"
  RUBY_VERSION = "4.0.5"
[context.deploy-preview.environment]
  HUGO_VERSION = "0.163.0"
  RUBY_VERSION = "4.0.5"
